TP MATHS - RELATIONS

In [4]:
def parties(E):

    if E ==[] : 
       return [[]]

    else : 
        x, EE = E[0], E[1:]
        
        tmp = parties(EE)
        return [ [x] + A for A in tmp] + tmp

def all_relations(n) :
    return parties([(x,y) for x in range(n) for y in range(n)])





In [5]:
all_relations(3)

[[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 2)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 1), (2, 2)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 1)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 2)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (2, 0), (2, 1), (2, 2)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (2, 0), (2, 1)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (2, 0), (2, 2)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (2, 0)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (2, 1), (2, 2)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (2, 1)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (2, 2)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1)],
 [(0, 0), (0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1)

In [6]:
def mat_adj(n,rel):
    mat = matrix(n)
    for i in range(n):
        for j in range(n):
            if(i,j) in rel:
                mat[i,j] = 1
    return mat

In [7]:
def all_matrices(n):
    liste = []
    for l in all_relations(n):
        liste.append( mat_adj(n,l))
    return liste

In [8]:
all_matrices(3)

[
[1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]
[1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]
[1 1 1], [1 1 0], [1 0 1], [1 0 0], [0 1 1], [0 1 0], [0 0 1], [0 0 0],

[1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]
[1 1 0]  [1 1 0]  [1 1 0]  [1 1 0]  [1 1 0]  [1 1 0]  [1 1 0]  [1 1 0]
[1 1 1], [1 1 0], [1 0 1], [1 0 0], [0 1 1], [0 1 0], [0 0 1], [0 0 0],

[1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]
[1 0 1]  [1 0 1]  [1 0 1]  [1 0 1]  [1 0 1]  [1 0 1]  [1 0 1]  [1 0 1]
[1 1 1], [1 1 0], [1 0 1], [1 0 0], [0 1 1], [0 1 0], [0 0 1], [0 0 0],

[1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]
[1 0 0]  [1 0 0]  [1 0 0]  [1 0 0]  [1 0 0]  [1 0 0]  [1 0 0]  [1 0 0]
[1 1 1], [1 1 0], [1 0 1], [1 0 0], [0 1 1], [0 1 0], [0 0 1], [0 0 0],

[1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]  [1 1 1]
[0 1 1]  [0 1 1]  [0 1 1]  [0 1 1]  [0 1 1]  [0 1 1]  [0 1 1]  [0 1

In [9]:
def reflexive(n,mat):
    for i in range(n):
        if(mat[i,i] == 0):
            return 0
    return 1
    
def symetrique(mat):
    return (mat.transpose() == mat)

def antisymetrique(n, mat):
    for i in range(n):
        for j in range(n):
            if(mat[i,j]== mat[j,i] and i!= j and mat[i,j]==1):
                return 0
            
    return 1
    
def transitive(n, mat):
    for i in range(n):
        for j in range(n):
            if(mat[i,j]):
                for k in range(n):
                    if(mat[j,k]):
                        if(mat[i,k] == 0):
                            return 0
    return 1


def test_mat(n):
    a,b,c,d = 0,0,0,0
    for m in all_matrices(n):
        a += reflexive(n,m)
        b += symetrique(m)
        c += antisymetrique(n,m)
        d += transitive(n,m)
        
    print("il y a %d matrices reflexives" % a)
    print("il y a %d matrices symetrique" % b)
    print("il y a %d matrices antisymetrique" % c)
    print("il y a %d matrices transitive" % d)

In [10]:
test_mat(3)

il y a 64 matrices reflexives
il y a 64 matrices symetrique
il y a 216 matrices antisymetrique
il y a 171 matrices transitive


Exercice 2

In [19]:
def getFermetureT(A):
    An,sommeA,B = A,A,A-A 
    while sommeA != B: 
        An = getBool(An * A) 
        B = sommeA
        sommeA = getBool(sommeA + An)
    return sommeA

def getBool(A):
    for i in range(A.ncols()):
        for j in range(A.nrows()):
            if(A[i,j] >1):
                A[i,j] =1
    return A



fermetures = []
for A in all_matrices(3):
    fermetures.append(getFermetureT(A))

    
ensemble = []
isIn = False

for f in fermetures:
    isIn = false
    for e in ensemble:
        if(e[0] == f):
            e[1] +=1
            isIn = True
            break
    if(not isIn):
        ensemble.append([f,1])
       
for e in ensemble:
        show(e[0], " : ",e[1])

[1 1 1]
[1 1 1]
[1 1 1] ' : ' 144

[1 1 1]
[1 1 1]
[0 0 1] ' : ' 12

[1 1 1]
[1 1 1]
[0 0 0] ' : ' 12

[1 1 1]
[0 1 1]
[0 1 1] ' : ' 12

[1 1 1]
[0 1 1]
[0 0 1] ' : ' 2

[1 1 1]
[0 1 1]
[0 0 0] ' : ' 2

[1 1 1]
[0 1 0]
[1 1 1] ' : ' 12

[1 1 1]
[0 1 0]
[0 1 1] ' : ' 2

[1 1 1]
[0 1 0]
[0 1 0] ' : ' 2

[1 1 1]
[0 1 0]
[0 0 1] ' : ' 1

[1 1 1]
[0 1 0]
[0 0 0] ' : ' 1

[1 1 1]
[0 0 1]
[0 0 1] ' : ' 2

[1 1 1]
[0 0 1]
[0 0 0] ' : ' 2

[1 1 1]
[0 0 0]
[1 1 1] ' : ' 12

[1 1 1]
[0 0 0]
[0 1 1] ' : ' 2

[1 1 1]
[0 0 0]
[0 1 0] ' : ' 2

[1 1 1]
[0 0 0]
[0 0 1] ' : ' 1

[1 1 1]
[0 0 0]
[0 0 0] ' : ' 1

[1 1 0]
[1 1 0]
[1 1 1] ' : ' 12

[1 1 0]
[1 1 0]
[1 1 0] ' : ' 12

[1 1 0]
[1 1 0]
[0 0 1] ' : ' 4

[1 1 0]
[1 1 0]
[0 0 0] ' : ' 4

[1 1 0]
[0 1 0]
[1 1 1] ' : ' 2

[1 1 0]
[0 1 0]
[1 1 0] ' : ' 2

[1 1 0]
[0 1 0]
[0 1 1] ' : ' 1

[1 1 0]
[0 1 0]
[0 1 0] ' : ' 1

[1 1 0]
[0 1 0]
[0 0 1] ' : ' 1

[1 1 0]
[0 1 0]
[0 0 0] ' : ' 1

[1 1 0]
[0 0 0]
[1 1 1] ' : ' 2

[1 1 0]
[0 0 0]
[1 1 0] ' : ' 2

[1 1 0]
[0 0 0]
[0 1 1] ' : ' 1

[1 1 0]
[0 0 0]
[0 1 0] ' : ' 1

[1 1 0]
[0 0 0]
[0 0 1] ' : ' 1

[1 1 0]
[0 0 0]
[0 0 0] ' : ' 1

[1 0 1]
[1 1 1]
[1 0 1] ' : ' 12

[1 0 1]
[1 1 1]
[0 0 1] ' : ' 2

[1 0 1]
[1 1 1]
[0 0 0] ' : ' 2

[1 0 1]
[1 0 1]
[1 0 1] ' : ' 12

[1 0 1]
[1 0 1]
[0 0 1] ' : ' 2

[1 0 1]
[1 0 1]
[0 0 0] ' : ' 2

[1 0 1]
[0 1 1]
[0 0 1] ' : ' 1

[1 0 1]
[0 1 1]
[0 0 0] ' : ' 1

[1 0 1]
[0 1 0]
[1 0 1] ' : ' 4

[1 0 1]
[0 1 0]
[0 0 1] ' : ' 1

[1 0 1]
[0 1 0]
[0 0 0] ' : ' 1

[1 0 1]
[0 0 1]
[0 0 1] ' : ' 1

[1 0 1]
[0 0 1]
[0 0 0] ' : ' 1

[1 0 1]
[0 0 0]
[1 0 1] ' : ' 4

[1 0 1]
[0 0 0]
[0 0 1] ' : ' 1

[1 0 1]
[0 0 0]
[0 0 0] ' : ' 1

[1 0 0]
[1 1 1]
[1 1 1] ' : ' 12

[1 0 0]
[1 1 1]
[1 0 1] ' : ' 2

[1 0 0]
[1 1 1]
[1 0 0] ' : ' 2

[1 0 0]
[1 1 1]
[0 0 1] ' : ' 1

[1 0 0]
[1 1 1]
[0 0 0] ' : ' 1

[1 0 0]
[1 1 0]
[1 1 1] ' : ' 2

[1 0 0]
[1 1 0]
[1 1 0] ' : ' 2

[1 0 0]
[1 1 0]
[1 0 1] ' : ' 1

[1 0 0]
[1 1 0]
[1 0 0] ' : ' 1

[1 0 0]
[1 1 0]
[0 0 1] ' : ' 1

[1 0 0]
[1 1 0]
[0 0 0] ' : ' 1

[1 0 0]
[1 0 1]
[1 0 1] ' : ' 2

[1 0 0]
[1 0 1]
[1 0 0] ' : ' 2

[1 0 0]
[1 0 1]
[0 0 1] ' : ' 1

[1 0 0]
[1 0 1]
[0 0 0] ' : ' 1

[1 0 0]
[1 0 0]
[1 1 1] ' : ' 2

[1 0 0]
[1 0 0]
[1 1 0] ' : ' 2

[1 0 0]
[1 0 0]
[1 0 1] ' : ' 1

[1 0 0]
[1 0 0]
[1 0 0] ' : ' 1

[1 0 0]
[1 0 0]
[0 0 1] ' : ' 1

[1 0 0]
[1 0 0]
[0 0 0] ' : ' 1

[1 0 0]
[0 1 1]
[0 1 1] ' : ' 4

[1 0 0]
[0 1 1]
[0 0 1] ' : ' 1

[1 0 0]
[0 1 1]
[0 0 0] ' : ' 1

[1 0 0]
[0 1 0]
[1 1 1] ' : ' 1

[1 0 0]
[0 1 0]
[1 1 0] ' : ' 1

[1 0 0]
[0 1 0]
[1 0 1] ' : ' 1

[1 0 0]
[0 1 0]
[1 0 0] ' : ' 1

[1 0 0]
[0 1 0]
[0 1 1] ' : ' 1

[1 0 0]
[0 1 0]
[0 1 0] ' : ' 1

[1 0 0]
[0 1 0]
[0 0 1] ' : ' 1

[1 0 0]
[0 1 0]
[0 0 0] ' : ' 1

[1 0 0]
[0 0 1]
[0 0 1] ' : ' 1

[1 0 0]
[0 0 1]
[0 0 0] ' : ' 1

[1 0 0]
[0 0 0]
[1 1 1] ' : ' 1

[1 0 0]
[0 0 0]
[1 1 0] ' : ' 1

[1 0 0]
[0 0 0]
[1 0 1] ' : ' 1

[1 0 0]
[0 0 0]
[1 0 0] ' : ' 1

[1 0 0]
[0 0 0]
[0 1 1] ' : ' 1

[1 0 0]
[0 0 0]
[0 1 0] ' : ' 1

[1 0 0]
[0 0 0]
[0 0 1] ' : ' 1

[1 0 0]
[0 0 0]
[0 0 0] ' : ' 1

[0 1 1]
[0 1 1]
[0 1 1] ' : ' 12

[0 1 1]
[0 1 1]
[0 0 1] ' : ' 2

[0 1 1]
[0 1 1]
[0 0 0] ' : ' 2

[0 1 1]
[0 1 0]
[0 1 1] ' : ' 2

[0 1 1]
[0 1 0]
[0 1 0] ' : ' 2

[0 1 1]
[0 1 0]
[0 0 1] ' : ' 1

[0 1 1]
[0 1 0]
[0 0 0] ' : ' 1

[0 1 1]
[0 0 1]
[0 0 1] ' : ' 2

[0 1 1]
[0 0 1]
[0 0 0] ' : ' 2

[0 1 1]
[0 0 0]
[0 1 1] ' : ' 2

[0 1 1]
[0 0 0]
[0 1 0] ' : ' 2

[0 1 1]
[0 0 0]
[0 0 1] ' : ' 1

[0 1 1]
[0 0 0]
[0 0 0] ' : ' 1

[0 1 0]
[0 1 0]
[1 1 1] ' : ' 2

[0 1 0]
[0 1 0]
[1 1 0] ' : ' 2

[0 1 0]
[0 1 0]
[0 1 1] ' : ' 1

[0 1 0]
[0 1 0]
[0 1 0] ' : ' 1

[0 1 0]
[0 1 0]
[0 0 1] ' : ' 1

[0 1 0]
[0 1 0]
[0 0 0] ' : ' 1

[0 1 0]
[0 0 0]
[1 1 1] ' : ' 2

[0 1 0]
[0 0 0]
[1 1 0] ' : ' 2

[0 1 0]
[0 0 0]
[0 1 1] ' : ' 1

[0 1 0]
[0 0 0]
[0 1 0] ' : ' 1

[0 1 0]
[0 0 0]
[0 0 1] ' : ' 1

[0 1 0]
[0 0 0]
[0 0 0] ' : ' 1

[0 0 1]
[1 1 1]
[0 0 1] ' : ' 2

[0 0 1]
[1 1 1]
[0 0 0] ' : ' 2

[0 0 1]
[1 0 1]
[0 0 1] ' : ' 2

[0 0 1]
[1 0 1]
[0 0 0] ' : ' 2

[0 0 1]
[0 1 1]
[0 0 1] ' : ' 1

[0 0 1]
[0 1 1]
[0 0 0] ' : ' 1

[0 0 1]
[0 1 0]
[0 0 1] ' : ' 1

[0 0 1]
[0 1 0]
[0 0 0] ' : ' 1

[0 0 1]
[0 0 1]
[0 0 1] ' : ' 1

[0 0 1]
[0 0 1]
[0 0 0] ' : ' 1

[0 0 1]
[0 0 0]
[0 0 1] ' : ' 1

[0 0 1]
[0 0 0]
[0 0 0] ' : ' 1

[0 0 0]
[1 1 1]
[1 1 1] ' : ' 12

[0 0 0]
[1 1 1]
[1 0 1] ' : ' 2

[0 0 0]
[1 1 1]
[1 0 0] ' : ' 2

[0 0 0]
[1 1 1]
[0 0 1] ' : ' 1

[0 0 0]
[1 1 1]
[0 0 0] ' : ' 1

[0 0 0]
[1 1 0]
[1 1 1] ' : ' 2

[0 0 0]
[1 1 0]
[1 1 0] ' : ' 2

[0 0 0]
[1 1 0]
[1 0 1] ' : ' 1

[0 0 0]
[1 1 0]
[1 0 0] ' : ' 1

[0 0 0]
[1 1 0]
[0 0 1] ' : ' 1

[0 0 0]
[1 1 0]
[0 0 0] ' : ' 1

[0 0 0]
[1 0 1]
[1 0 1] ' : ' 2

[0 0 0]
[1 0 1]
[1 0 0] ' : ' 2

[0 0 0]
[1 0 1]
[0 0 1] ' : ' 1

[0 0 0]
[1 0 1]
[0 0 0] ' : ' 1

[0 0 0]
[1 0 0]
[1 1 1] ' : ' 2

[0 0 0]
[1 0 0]
[1 1 0] ' : ' 2

[0 0 0]
[1 0 0]
[1 0 1] ' : ' 1

[0 0 0]
[1 0 0]
[1 0 0] ' : ' 1

[0 0 0]
[1 0 0]
[0 0 1] ' : ' 1

[0 0 0]
[1 0 0]
[0 0 0] ' : ' 1

[0 0 0]
[0 1 1]
[0 1 1] ' : ' 4

[0 0 0]
[0 1 1]
[0 0 1] ' : ' 1

[0 0 0]
[0 1 1]
[0 0 0] ' : ' 1

[0 0 0]
[0 1 0]
[1 1 1] ' : ' 1

[0 0 0]
[0 1 0]
[1 1 0] ' : ' 1

[0 0 0]
[0 1 0]
[1 0 1] ' : ' 1

[0 0 0]
[0 1 0]
[1 0 0] ' : ' 1

[0 0 0]
[0 1 0]
[0 1 1] ' : ' 1

[0 0 0]
[0 1 0]
[0 1 0] ' : ' 1

[0 0 0]
[0 1 0]
[0 0 1] ' : ' 1

[0 0 0]
[0 1 0]
[0 0 0] ' : ' 1

[0 0 0]
[0 0 1]
[0 0 1] ' : ' 1

[0 0 0]
[0 0 1]
[0 0 0] ' : ' 1

[0 0 0]
[0 0 0]
[1 1 1] ' : ' 1

[0 0 0]
[0 0 0]
[1 1 0] ' : ' 1

[0 0 0]
[0 0 0]
[1 0 1] ' : ' 1

[0 0 0]
[0 0 0]
[1 0 0] ' : ' 1

[0 0 0]
[0 0 0]
[0 1 1] ' : ' 1

[0 0 0]
[0 0 0]
[0 1 0] ' : ' 1

[0 0 0]
[0 0 0]
[0 0 1] ' : ' 1

[0 0 0]
[0 0 0]
[0 0 0] ' : ' 1

In [20]:
len(ensemble)

171

In [21]:
summary = {}


for i in ensemble:
    isIn = false
    for j in summary.keys():
        if(i[1] == j):
            summary[i[1]] += 1
            isIn = True
            break
    if(not isIn):
        summary[i[1]] = 1
        
summary

{144: 1, 12: 12, 2: 48, 1: 104, 4: 6}

In [22]:
sum = 0
for i in summary.keys():
    sum += i * summary.get(i)
    
sum

512

Exercice 3

In [28]:
def Q(n,rand):
    A = matrix(n)
    for i in range(0,n):
        for j in range(0,n):
            if(random() <= rand):
                A[i,j] = 1
            else:
                A[i,j] = 0
    return A

def R(A,n):
    if not  reflexive(n,A):
        for i in range(n):
            A[i,i] = 1
    return A

def S(A,n):
    if not symetrique(A):
        for i in range(n):
            for j in range(n):
                if(A[i,j] and not A[j,i] ):
                    A[j,i] = 1
                        
    return A


def T(A,n):
    if not transitive(n,A):
        for i in range(n):
            for j in range(n):
                if(A[i,j]):
                    for k in range(n):
                        if(A[j,k]):
                            A[i,k]= 1
                        
    return A

In [37]:
import numpy
q = Q(50,0.01)

r = R(q,50)
s = S(r,50)
t = T(s,50)


print(t)



[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0]
[0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1

Bonus : Plus on augmente la probabilité de placer des 1, et plus la matrice aura de chance d'etre composée uniquement de 1 une fois devenu reflexive, transitive et symmétrique